#!/usr/bin/env bash

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

################################################################################
# Code from p4.org
container_id=${P4APP_NAME:-$(docker ps | grep -m1 p4app_ | awk '{print $1}')}

if [ -z "$container_id" ]; then
    echo "Couldn't find any p4app currently running."
    exit 1
fi
# End of code from p4.org
################################################################################

docker cp $SCRIPTPATH/traffic_generation $container_id:/scripts

echo Done!
