#!/usr/bin/env bash

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`
TAG_PREFIX="lucashagen/zeek-"

BUILT_IMAGE=false

if [ "$1" = "base" ] || [ "$1" = "all" ] ; then

    echo ""
    echo "-- BASE --"
    echo ""
    docker build --tag ${TAG_PREFIX}base -f $SCRIPTPATH/docker/base/Dockerfile .
    BUILT_IMAGE=true

fi

if [ "$1" = "full" ] || [ "$1" = "full42" ] || [ "$1" = "all" ] ; then

    echo ""
    echo "-- FULL:4.2 && FULL:latest --"
    echo ""
    docker build --tag ${TAG_PREFIX}full:4.2 \
        -f $SCRIPTPATH/docker/full/Dockerfile \
        --build-arg ZEEK_PACKAGE=zeek-rc \
        --build-arg ZEEK_PATH=/opt/zeek-rc \
        --build-arg ZEEK_DIST_SOURCE=deps/zeek42 \
        .

    docker tag ${TAG_PREFIX}full:4.2 ${TAG_PREFIX}full:latest

    BUILT_IMAGE=true

fi

if [ "$1" = "dev" ] || [ "$1" = "all" ] ; then

    echo ""
    echo "-- DEV --"
    echo ""
    docker build --tag ${TAG_PREFIX}dev -f $SCRIPTPATH/docker/dev/Dockerfile .
    BUILT_IMAGE=true

fi

if [ "$BUILT_IMAGE" = true ] ; then

    echo ""
    echo ""
    echo "Done building!"

else

    echo "Correct usage: ./build-image <base|full|full42|full40|dev|all>"

fi
