#!/usr/bin/env bash

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`
P4APP=$SCRIPTPATH/deps/p4app/p4app

if [ -f "$P4APP" ]; then
    $P4APP "$@"
else
    echo "Error: p4app not found"
    echo "Initialize submodules: ./init-submodules"
fi
