#!/usr/bin/env bash

SCRIPT_PATH=`realpath $0`
SCRIPT_NAME=`basename $SCRIPT_PATH`
SCRIPT_DIR=`dirname $SCRIPT_PATH`

EXEC_FILES="$SCRIPT_DIR/exec_files"

if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
    echo "This prepares your ZPO output folder with all required files for you to run it using docker."
    echo ""
    echo "Usage: ./$SCRIPT_NAME <zpo_output_dir>"
    exit
fi

if [ -z "$1" ]
then
    echo "Error! Correct usage: ./$SCRIPT_NAME <zpo_output_dir>"
    exit
fi

OUTPUT_DIR=`realpath $1`

ZEEK_OUTPUT="$OUTPUT_DIR/zpo.zeek"
P4_OUTPUT="$OUTPUT_DIR/zpo.p4app"

if [ ! -d "$1" ] || [ ! -d "$1/zpo.zeek" ] || [ ! -d "$1/zpo.zeek" ]
then
    echo "Error! '$1' is not a valid ZPO output folder! Did you run ZPO?"
    exit
fi


echo "Preparing executable ZPO at '$1'"

cp "$EXEC_FILES/p4app.json" "$P4_OUTPUT/"
cp "$EXEC_FILES/zpo.config" "$P4_OUTPUT/"

cp "$EXEC_FILES/run_zeek" "$OUTPUT_DIR/"
cp "$EXEC_FILES/run_zeek_traces" "$OUTPUT_DIR/"
cp "$EXEC_FILES/run" "$ZEEK_OUTPUT/"
cp "$EXEC_FILES/run_all" "$ZEEK_OUTPUT/"
cp "$EXEC_FILES/clean" "$ZEEK_OUTPUT/"
cp "$EXEC_FILES/install" "$ZEEK_OUTPUT/"
# cp "$EXEC_FILES/profiler.py" "$ZEEK_OUTPUT/"

echo "$SCRIPT_DIR/p4app run $P4_OUTPUT" > $OUTPUT_DIR/run_p4app

chmod +x "$OUTPUT_DIR/run_zeek_traces"
chmod +x "$OUTPUT_DIR/run_p4app"
chmod +x "$ZEEK_OUTPUT/run"
chmod +x "$ZEEK_OUTPUT/run_all"
chmod +x "$ZEEK_OUTPUT/clean"
chmod +x "$ZEEK_OUTPUT/install"
# chmod +x "$ZEEK_OUTPUT/profiler.py"

echo "Done!"
