#!/usr/bin/env bash

SCRIPT_PATH=`realpath $0`
SCRIPT_NAME=`basename $SCRIPT_PATH`
SCRIPT_DIR=`dirname $SCRIPT_PATH`

FILES_DIR="$SCRIPT_DIR/to_merge"

OUTPUT_FILE="$SCRIPT_DIR/full_dataset.pcapng"
OUTPUT_FILE_SHA256="74feb7c9ed8a1d0f57a52a419785713f8c3e087523872791053498f8ef173c5e"

GZ_EQUINIX_FILE="$SCRIPT_DIR/CAIDA/equinix-chicago.dirA.20160406-130700.UTC.anon.pcap.gz"
GZ_EQUINIX_FILE_SHA256="72440cb663607a735d3eccee30d65d94b34a83f7b1be7a18ab63ae32ea617503"

EQUINIX_FILE="$SCRIPT_DIR/CAIDA/equinix-chicago.dirA.20160406-130700.UTC.anon.pcap"
EQUINIX_FILE_SHA256="3c4493fe28182288249f550e950018f7be33c735183e79dfe43bef84d38efafb"

TRACE_PART="$SCRIPT_DIR/CAIDA/equinix-chicago.dirA.20160406-130700.UTC.anon_00003_20160406100730.pcap"
TRACE_PART_SHA256="95f28aed67136b86ec0ae0396af36fddca6f118f0ebe3ff32ce42e8dd42781bc"

ATTACKS_FILE="$SCRIPT_DIR/attacks.pcapng"
ATTACKS_FILE_SHA256="61bf26889e311c87d20bca598beaa8b6114701f367757009cedafc2ab6aa5991"

echo "Generating complete dataset at '$OUTPUT_FILE'"

if [ ! $(sha256sum $GZ_EQUINIX_FILE | awk '{print $1}') = "$GZ_EQUINIX_FILE_SHA256" ] ; then
    echo "Error: sha256sum mismatch for '$GZ_EQUINIX_FILE'"
    exit 1
else
    echo "Equinix/CAIDA file sha256sum matches!"
fi

echo "Decompressing equinix file"

gunzip -c $GZ_EQUINIX_FILE > $EQUINIX_FILE

echo "Splitting equinix file into 10 seconds window"

editcap -i 10 $EQUINIX_FILE $EQUINIX_FILE

echo "Merging all attack pcaps"

mergecap -w $ATTACKS_FILE $FILES_DIR/*.pcapng

if [ ! $(sha256sum $ATTACKS_FILE | awk '{print $1}') = "$ATTACKS_FILE_SHA256" ] ; then
    echo "Error: sha256sum mismatch for '$ATTACKS_FILE'"
    exit 1
fi

echo "Merging attacks with equinix (10s window) file"

mergecap -w $OUTPUT_FILE $TRACE_PART $ATTACKS_FILE

if [ ! $(sha256sum $OUTPUT_FILE | awk '{print $1}') = "$OUTPUT_FILE_SHA256" ] ; then
    echo "Error: sha256sum mismatch for '$OUTPUT_FILE'"
    exit 1
fi


echo "Done! Saved as: $OUTPUT_FILE"
