#!/usr/bin/env bash

SCRIPT_PATH=`realpath $0`
SCRIPT_NAME=`basename $SCRIPT_PATH`
SCRIPT_DIR=`dirname $SCRIPT_PATH`

for filename in $SCRIPT_DIR/*.pcapng; do
    capinfos "$filename" > "$filename.txt"
    echo Generated \'`basename $filename.txt`\'
done

echo ""
echo "Done!"
