#pragma once

#define TYPE_EVENT_L3 0x6606

namespace zeek::packet_analysis::BR_INF_UFRGS_ZPO {

/**
 * @brief Generic event packet generated by the P4 switch.
 */
typedef struct event_t_struct {
    uint32_t pkt_num;      // 4
    uint16_t protocol_l3;  // 2
    uint16_t protocol_l4;  // 2
    uint8_t src_addr[4];   // 4
    uint8_t dst_addr[4];   // 4
    uint16_t src_port;     // 2
    uint16_t dst_port;     // 2
    uint16_t type;         // 2
} event_t;

}  // namespace zeek::packet_analysis::BR_INF_UFRGS_ZPO

// header event_t {
//     bit<32> pkt_num;        // 4
//     bit<16> protocol_l3;    // 2
//     bit<16> protocol_l4;    // 2
//     bit<32> src_addr;       // 4
//     bit<32> dst_addr;       // 4
//     bit<16> src_port;       // 2
//     bit<16> dst_port;       // 2
//     bit<16> type;           // 2
// }
