#!/usr/bin/env bash

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`

echo ""
echo "-- BASE --"
echo ""
docker build --tag lucashagen/zeek-base $SCRIPTPATH/base

echo ""
echo "-- FULL:LTS --"
echo ""
docker build --tag lucashagen/zeek-apt:lts $SCRIPTPATH/apt

echo ""
echo "-- FULL:RC --"
echo ""
docker build --tag lucashagen/zeek-apt:rc --build-arg ZEEK_PACKAGE="zeek-rc" --build-arg ZEEK_PATH="/opt/zeek-rc" $SCRIPTPATH/apt

echo ""
echo "-- FULL:LATEST --"
echo ""
docker build --tag lucashagen/zeek-full --build-arg $SCRIPTPATH/apt

# for d in ./* ; do
#     [ -d "$d" ] && [ ! -L "$d" ] || continue

#     d_name=$(basename -- "$d")
#     image_name="lucashagen/zeek-$d_name"

#     echo "Building '$image_name':"
#     docker build --tag $image_name $d
# done

echo ""
echo ""
echo "Done building images!"
